### ISSUE TITLE
PanicException with 0.4.*

### ISSUE THREAD

**Issue by MiniXC** [bminixhofer/nnsplit#19]
After installing the new version, I get the following exception when running ``NNSplit.load("en")``.

````
PanicException: called `Result::unwrap()` on an `Err` value: PyErr { type: Py(0x5632cc1b1140, PhantomData) }
````
This occurs both with and without ``onnxruntime-gpu`` installed.

**Comment by MiniXC** [comment]
I think this could be because I still have an old version of the model cached somewhere, is there some way to clear the cache?

**Comment by bminixhofer** [comment]
Weird. You can try clearing the cache, probably at `~/.cache/nnsplit/` on Linux. But I don't see how the cache could be a problem, the model hasn't changed since 0.3.x. I'll look into better reporting of errors from Python.

**Comment by MiniXC** [comment]
haha just a prank, it works now

**Comment by bminixhofer** [comment]
For anyone else with this problem: `pip install --upgrade --ignore-installed nnsplit` seems to have fixed this here.

**Comment by MiniXC** [comment]
When getting PanicExceptions when using gpu, downgrading to ``onnxruntime-gpu==1.4.0`` fixed it for me.
