### ISSUE TITLE
Can't run it on macOS

### ISSUE THREAD

**Issue by TakamotoAI** [bminixhofer/nnsplit#48]
I want to give the module a try, but I am getting the following error by running the basic example on the readme. Module was installed with pip.

splitter = NNSplit.load("en")
AttributeError: type object 'NNSplit' has no attribute 'load'

**Comment by bminixhofer** [comment]
Hi, sorry for the late response.

Which Python version are you using? And can you do `pip freeze | grep nnsplit` to check the NNSplit version?

It seems like an old version might have been installed. You can try installing the correct wheel from [here](https://pypi.org/project/nnsplit/0.5.7-post0/#files).

**Comment by bminixhofer** [comment]
Closing this as stale.
