### ISSUE TITLE
Security: update version of tract-onnx

### ISSUE THREAD

**Issue by cjrh** [bminixhofer/nnsplit#50]
This security vulnerability: 

https://rustsec.org/advisories/RUSTSEC-2021-0073.html

is fixed in prost==0.8.0, which is included in a recent new release of tract-onnx: https://github.com/sonos/tract/releases/tag/0.15.2

Would it be possible to do a new release with the tract-onnx dependency bumped?

**Comment by bminixhofer** [comment]
Hi, thanks for letting me know! I'll bump it, and take that opportunity to implement https://github.com/bminixhofer/nnsplit/issues/30#issuecomment-853590478 since the required changes are released now.

**Comment by bminixhofer** [comment]
I was on holiday last week. Back now and as of v0.5.8 this is fixed!
