### ISSUE TITLE
Python 3.10 wheel

### ISSUE THREAD

**Issue by cjrh** [bminixhofer/nnsplit#64]
It seems there is no wheel for Python 3.10 on PyPI yet: https://pypi.org/project/nnsplit/#files

Is there anything I can do to help with 3.10 support?

**Comment by bminixhofer** [comment]
Hi, thanks for letting me know! It should be fairly trivial to build wheels for 3.10. Will try it now, and update you here if there's any issues.

**Comment by cjrh** [comment]
Thank you anyway for looking so quickly!

**Comment by wallies** [comment]
@bminixhofer onnxruntime have just pushed 3.10 wheels for the new version 1.12. Does this mean you can build wheels for 3.10 now or does it need a lot more work?

**Comment by darxkies** [comment]
Any news about the 3.10 wheel?

**Comment by bminixhofer** [comment]
Hi, thanks to @wallies, Python 3.10 is now supported in Version 5.9! #75
